const dataEvents = [
  {
    "id": "0",
    "game_id": "0",
    "name": "Открытый кубок ВК",
    "code": null, 
    "description": "Турнир 5х5",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  },
  {
    "id": "1",
    "game_id":"0",
    "name":"Mid Masters",
    "code": null, 
    "description": "1 на 1",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  },{
    "id": "2",
    "game_id":"0",
    "name":"The Aegis Defensive",
    "code": null, 
    "description": "The Aegis Defensive",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  }, 
  {
    "id": "10",
    "game_id": "1",
    "name": "МТС Онлайн",
    "code": null, 
    "description": "Турнир 5х5",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  },
  {
    "id": "11",
    "game_id":"1",
    "name":"Лига Справедливости",
    "code": null, 
    "description": "1 на 1",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  },{
    "id": "12",
    "game_id":"1",
    "name":"ASD 23",
    "code": null, 
    "description": "The Aegis Defensive",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  }, 

  {
    "id": "20",
    "game_id": "2",
    "name": "CS.GO Noobs",
    "code": null, 
    "description": "Турнир 5х5",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  },
  {
    "id": "21",
    "game_id":"2",
    "name":"ESL 300A",
    "code": null, 
    "description": "1 на 1",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  },{
    "id": "22",
    "game_id":"2",
    "name":"SBER 3",
    "code": null, 
    "description": "The Aegis Defensive",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  },
  
  {
    "id": "30",
    "game_id": "3",
    "name": "World of tanks",
    "code": null, 
    "description": "Турнир 5х5",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  },
  {
    "id": "31",
    "game_id":"3",
    "name":"Tanks & Lays",
    "code": null, 
    "description": "1 на 1",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  },{
    "id": "32",
    "game_id":"3",
    "name":"World of tanks",
    "code": null, 
    "description": "The Aegis Defensive",
    "date_time": null,
    "start_time": null,
    "finish_time": null,
    "checkin_time": null,
    "favorites": false,
    "players": [],
      "image":"https://code.s3.yandex.net/react/code/bun-02.png",
      "image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png"      
  },
];
  
  // TODO Экспорт данных для использования в компонентах
  export default dataEvents;
  